[tool.poetry]
name = "jsync"
version = "0.1.6"
description = "Tool to run rsync utility in parallel"
authors = ["Vladimir Grebenshchikov <vova@zote.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
humanize = "^4.9"
rich = "^13.7"

[tool.poetry.scripts]
jsync = "jsync:synchronize"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]


